terminate called after throwing an instance of 'std::bad_alloc'
what():  std::bad_alloc
/bin/bash: line 1: 19208 Aborted